/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasipengelolakrs;

import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class MenuCekKRS extends javax.swing.JFrame {

    /**
     * Creates new form MenuCekKRS
     */
    public MenuCekKRS() {
        initComponents();
        showData();
        btnHapusKRS.setEnabled(false);
        btnCetakKRS.setEnabled(false);
    }
    
    String id;
    Connection con = koneksiSql.getKoneksi();
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKRS = new javax.swing.JTable();
        btnHapusKRS = new javax.swing.JButton();
        btnCariData = new javax.swing.JButton();
        txtCariData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCetakKRS = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lihat Data KRS Disini"));

        tableKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKRS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKRSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKRS);

        btnHapusKRS.setText("Hapus KRS");
        btnHapusKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKRSActionPerformed(evt);
            }
        });

        btnCariData.setText("Cari Data");
        btnCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDataActionPerformed(evt);
            }
        });

        jLabel2.setText("Cari Data KRS Berdasarkan Nama");

        btnCetakKRS.setText("Cetak KRS");
        btnCetakKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKRSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCariData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCetakKRS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusKRS)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusKRS)
                    .addComponent(btnCariData)
                    .addComponent(txtCariData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnCetakKRS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU INPUT KRS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKRSActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,"Hapus Data KRS Ini?", "Konfirmasi Hapus", 0);
                
            if (confirm == 0) { // untuk jika memilih ya saat joption muncul akan menghapus datanya
                try {
                    String queryHapus = "DELETE FROM krs WHERE id = ?;";
                    pst = con.prepareStatement(queryHapus);
                    pst.setString(1, id);
                    pst.executeUpdate();
                        
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!!", "Sukses Menghapus", 1);
                    showData();
                } catch (SQLException ex) {
                    Logger.getLogger(MenuCekKRS.class.getName()).log(Level.SEVERE, null, ex);
                }            
            }
    }//GEN-LAST:event_btnHapusKRSActionPerformed

    private void btnCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDataActionPerformed
        showData();
    }//GEN-LAST:event_btnCariDataActionPerformed

    private void tableKRSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKRSMouseClicked
        int row = tableKRS.getSelectedRow();
        id = tableKRS.getValueAt(row, 0).toString();
        btnHapusKRS.setEnabled(true);
        btnCetakKRS.setEnabled(true);
    }//GEN-LAST:event_tableKRSMouseClicked

    private void btnCetakKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKRSActionPerformed
        int row = tableKRS.getSelectedRow();
        id = tableKRS.getValueAt(row, 0).toString();
        
        StringBuilder content = new StringBuilder();
        content.append("Data KRS Universitas Teknologi Kalsel Anda :").append("\n\n");
            
        content.append("Nama : ").append(tableKRS.getValueAt(row, 1).toString()).append("\n");
        content.append("NPM : ").append(tableKRS.getValueAt(row, 2).toString()).append("\n");
        content.append("Semester : ").append(tableKRS.getValueAt(row, 3).toString()).append("\n");
        content.append("Kelas : ").append(tableKRS.getValueAt(row, 4).toString()).append("\n");
        content.append("Mata Kuliah 1 : ").append(tableKRS.getValueAt(row, 5).toString()).append("\n");
        content.append("Mata Kuliah 2 : ").append(tableKRS.getValueAt(row, 6).toString()).append("\n");
        content.append("Mata Kuliah 3 : ").append(tableKRS.getValueAt(row, 7).toString()).append("\n");
        content.append("Mata Kuliah 4 : ").append(tableKRS.getValueAt(row, 8).toString()).append("\n");
        content.append("Mata Kuliah 5 : ").append(tableKRS.getValueAt(row, 9).toString()).append("\n");
        content.append("Mata Kuliah 6 : ").append(tableKRS.getValueAt(row, 10).toString()).append("\n");
            
            
            
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Data Alamat");
        int userSelection = fileChooser.showSaveDialog(this);
            
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            try (FileWriter fileWriter = new FileWriter(fileChooser.getSelectedFile() + ".txt")) {
                fileWriter.write(content.toString());
                JOptionPane.showMessageDialog(this, "Data kontak berhasil disimpan ke Perangkat");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCetakKRSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCekKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCekKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCekKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCekKRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCekKRS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariData;
    private javax.swing.JButton btnCetakKRS;
    private javax.swing.JButton btnHapusKRS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKRS;
    private javax.swing.JTextField txtCariData;
    // End of variables declaration//GEN-END:variables

    private void showData() {
        try {
            String[] judul = {"ID", "Nama", "NPM", "Semester", "Kelas" , "Matkul 1", "Matkul 2", "Matkul 3", "Matkul 4", "Matkul 5", "Matkul 6"};
            DefaultTableModel dtm = new DefaultTableModel(null, judul);
            tableKRS.setModel(dtm);
            
            String sql = "SELECT * FROM krs";
            
            if (!txtCariData.getText().isEmpty()) {
                    sql = "SELECT * FROM krs WHERE nama LIKE '%" + txtCariData.getText() + "%';";
            }
            
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String[] data = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11)};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuCekKRS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
